name: Build Go Program for ARM64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        architecture: [ arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Specify the Go version you need

      - name: Build for ARM64
        run: |
          GOARCH=arm64 GOOS=linux go build -v -o output-arm64 ./...

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-build-arm64
          path: output-arm64
